[DSD-3666] updated the readme.md for mimoto installation
mosip/mimoto pull request #138
Opened 2023-10-24 10:22 UTC by Rakshitha650

2023-10-24 11:04 UTC, syedsalman3753 requested changes

2023-10-24 11:04 UTC, syedsalman3753 commented on README.md
> +* Once the job is completed, log in to Minio and check the reports. There should not be any failures.
Replace minio with S3

2023-10-24 11:20 UTC, syedsalman3753 approved these changes

2023-10-27 05:12 UTC, ckm007 commented on README.md
> +1. run Onboarder install
Execute instead of run

2023-10-27 10:28 UTC, SwatiPeriwal commented on README.md
> +* During the execution of the 'install.sh' script, a prompt appears requesting information for the S3 bucket, including its name and URL.
* During the execution of the `install.sh` script, a prompt appears requesting information for the S3 bucket, including its name and URL.

2023-10-27 10:31 UTC, SwatiPeriwal commented on README.md
> +1. Execute Onboarder install
Complete the sentence if possible...

2023-10-27 10:31 UTC, SwatiPeriwal approved these changes
Update changes and then proceed with merge

2023-10-27 12:21 UTC, SwatiPeriwal approved these changes
Approved

2023-10-27 14:13 UTC, ckm007 approved these changes

2023-10-27 14:15 UTC, merged