Task INJIMOB-1568
mosip/mimoto pull request #294
Opened 2024-07-08 11:27 UTC by santhoshsunder

adding descriptions to the API scenarios

2024-08-14 09:57 UTC, mohanachandran-s requested changes

2024-08-14 09:57 UTC, mohanachandran-s commented on apitest/src/main/resources/mimoto/AidGetIndividualId/AidGetIndividualId.yml
> +      endPoint: v1/mimoto/aid/get-individual-id
Endpoint shouldn't be changed here

2024-08-14 09:57 UTC, mohanachandran-s commented on apitest/src/main/resources/mimoto/AuthLock/createAuthLock.yml
> +      endPoint: //v1/mimoto/req/auth/lock
Endpoint shouldn't be changed here

2024-08-14 09:57 UTC, mohanachandran-s commented on apitest/src/main/resources/mimoto/AuthLock/createAuthLock.yml
> +      endPoint: mimoto/AuthLock/createAuthLock
Endpoint shouldn't be changed here

2024-08-14 09:57 UTC, mohanachandran-s commented on apitest/src/main/resources/mimoto/AuthUnLock/createAuthUnLock.yml
> +      endPoint: v1/mimoto/req/auth/unlock
Endpoint shouldn't be changed here

2024-08-14 09:57 UTC, mohanachandran-s commented on apitest/src/main/resources/mimoto/BindingOtp/BindingOtp.yml
> +      endPoint: /v1/mimoto/binding-ot
Endpoint shouldn't be changed here

2024-08-14 09:57 UTC, mohanachandran-s commented on apitest/src/main/resources/mimoto/BindingOtp/BindingOtp.yml
> -      endPoint: /v1/mimoto/binding-otp
Endpoint shouldn't be changed here

2024-08-30 12:05 UTC, santhoshsunder commented on apitest/src/main/resources/mimoto/AuthLock/createAuthLock.yml
> +      endPoint: //v1/mimoto/req/auth/lock
changes done

2024-08-30 12:05 UTC, santhoshsunder commented on apitest/src/main/resources/mimoto/AuthUnLock/createAuthUnLock.yml
> +      endPoint: v1/mimoto/req/auth/unlock
changes done

2024-08-30 12:05 UTC, santhoshsunder commented on apitest/src/main/resources/mimoto/AuthLock/createAuthLock.yml
> +      endPoint: mimoto/AuthLock/createAuthLock
changes done

2024-08-30 12:05 UTC, santhoshsunder commented on apitest/src/main/resources/mimoto/BindingOtp/BindingOtp.yml
> +      endPoint: /v1/mimoto/binding-ot
changes done

2024-08-30 12:06 UTC, santhoshsunder commented on apitest/src/main/resources/mimoto/BindingOtp/BindingOtp.yml
> -      endPoint: /v1/mimoto/binding-otp
changes done

2024-08-30 13:09 UTC, mohanachandran-s approved these changes

2024-09-02 11:39 UTC, ckm007 approved these changes

2024-09-02 11:39 UTC, merged