[MOSIP-27194] Added helm-chart and deployment script for Mimoto in mimoto repo
mosip/mimoto pull request #84
Opened 2023-05-12 08:11 UTC by gaganamadival

2023-05-12 11:45 UTC, syedsalman3753 requested changes

2023-05-12 11:45 UTC, syedsalman3753 commented on helm/mimoto/Chart.yaml
> +  - mimoto
duplicate mimoto keyword

2023-05-12 11:45 UTC, syedsalman3753 commented on partner-onboarder/install.sh
> +  ENABLE_INSECURE='--set onboarding.enableInsecure=true';
@gaganamadival please update ENABLE_INSECURE value

```
ENABLE_INSECURE='--set onboarding.configmaps.onboarding.ENABLE_INSECURE=true
```

2023-05-12 11:52 UTC, syedsalman3753 approved these changes

2023-05-15 15:18 UTC, syedsalman3753 requested changes

2023-05-15 15:18 UTC, syedsalman3753 commented on partner-onboarder/install.sh
> +echo "n: if you don't have public domain & valid ssl certificate"
Update the above echo message

echo "n: If you don't have a public domain and a valid SSL certificate. Note: It is recommended to use this option only in development environments."

2023-05-16 04:45 UTC, syedsalman3753 approved these changes

2023-05-17 12:25 UTC, syedsalman3753 approved these changes

2023-05-17 13:02 UTC, ckm007 approved these changes

2023-05-17 13:02 UTC, merged